// Generated by gencpp from file test_roscpp/CustomHeader.msg
// DO NOT EDIT!


#ifndef TEST_ROSCPP_MESSAGE_CUSTOMHEADER_H
#define TEST_ROSCPP_MESSAGE_CUSTOMHEADER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_roscpp
{
template <class ContainerAllocator>
struct CustomHeader_
{
  typedef CustomHeader_<ContainerAllocator> Type;

  CustomHeader_()
    : a(0)  {
    }
  CustomHeader_(const ContainerAllocator& _alloc)
    : a(0)  {
  (void)_alloc;
    }



   typedef uint32_t _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::test_roscpp::CustomHeader_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_roscpp::CustomHeader_<ContainerAllocator> const> ConstPtr;

}; // struct CustomHeader_

typedef ::test_roscpp::CustomHeader_<std::allocator<void> > CustomHeader;

typedef boost::shared_ptr< ::test_roscpp::CustomHeader > CustomHeaderPtr;
typedef boost::shared_ptr< ::test_roscpp::CustomHeader const> CustomHeaderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_roscpp::CustomHeader_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_roscpp::CustomHeader_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_roscpp::CustomHeader_<ContainerAllocator1> & lhs, const ::test_roscpp::CustomHeader_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_roscpp::CustomHeader_<ContainerAllocator1> & lhs, const ::test_roscpp::CustomHeader_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_roscpp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::test_roscpp::CustomHeader_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_roscpp::CustomHeader_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_roscpp::CustomHeader_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_roscpp::CustomHeader_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_roscpp::CustomHeader_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_roscpp::CustomHeader_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_roscpp::CustomHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a5233fa4f3f6e00d1d85da1779d19d1e";
  }

  static const char* value(const ::test_roscpp::CustomHeader_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa5233fa4f3f6e00dULL;
  static const uint64_t static_value2 = 0x1d85da1779d19d1eULL;
};

template<class ContainerAllocator>
struct DataType< ::test_roscpp::CustomHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_roscpp/CustomHeader";
  }

  static const char* value(const ::test_roscpp::CustomHeader_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_roscpp::CustomHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 a\n"
;
  }

  static const char* value(const ::test_roscpp::CustomHeader_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_roscpp::CustomHeader_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomHeader_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_roscpp::CustomHeader_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_roscpp::CustomHeader_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_ROSCPP_MESSAGE_CUSTOMHEADER_H
