// Generated by gencpp from file test_roscpp/EmbeddedFixedLength.msg
// DO NOT EDIT!


#ifndef TEST_ROSCPP_MESSAGE_EMBEDDEDFIXEDLENGTH_H
#define TEST_ROSCPP_MESSAGE_EMBEDDEDFIXEDLENGTH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <test_roscpp/FixedLength.h>

namespace test_roscpp
{
template <class ContainerAllocator>
struct EmbeddedFixedLength_
{
  typedef EmbeddedFixedLength_<ContainerAllocator> Type;

  EmbeddedFixedLength_()
    : a()  {
    }
  EmbeddedFixedLength_(const ContainerAllocator& _alloc)
    : a(_alloc)  {
  (void)_alloc;
    }



   typedef  ::test_roscpp::FixedLength_<ContainerAllocator>  _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator> const> ConstPtr;

}; // struct EmbeddedFixedLength_

typedef ::test_roscpp::EmbeddedFixedLength_<std::allocator<void> > EmbeddedFixedLength;

typedef boost::shared_ptr< ::test_roscpp::EmbeddedFixedLength > EmbeddedFixedLengthPtr;
typedef boost::shared_ptr< ::test_roscpp::EmbeddedFixedLength const> EmbeddedFixedLengthConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator1> & lhs, const ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator1> & lhs, const ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_roscpp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator> >
{
  static const char* value()
  {
    return "770e15962592d1fbea70b6b820ba16d9";
  }

  static const char* value(const ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x770e15962592d1fbULL;
  static const uint64_t static_value2 = 0xea70b6b820ba16d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_roscpp/EmbeddedFixedLength";
  }

  static const char* value(const ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator> >
{
  static const char* value()
  {
    return "FixedLength a\n"
"\n"
"================================================================================\n"
"MSG: test_roscpp/FixedLength\n"
"uint32 a\n"
"float32 b\n"
;
  }

  static const char* value(const ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EmbeddedFixedLength_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_roscpp::EmbeddedFixedLength_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    s << std::endl;
    Printer< ::test_roscpp::FixedLength_<ContainerAllocator> >::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_ROSCPP_MESSAGE_EMBEDDEDFIXEDLENGTH_H
