// Generated by gencpp from file test_roscpp/WithMemberNamedHeaderThatIsNotAHeader.msg
// DO NOT EDIT!


#ifndef TEST_ROSCPP_MESSAGE_WITHMEMBERNAMEDHEADERTHATISNOTAHEADER_H
#define TEST_ROSCPP_MESSAGE_WITHMEMBERNAMEDHEADERTHATISNOTAHEADER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <test_roscpp/CustomHeader.h>

namespace test_roscpp
{
template <class ContainerAllocator>
struct WithMemberNamedHeaderThatIsNotAHeader_
{
  typedef WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator> Type;

  WithMemberNamedHeaderThatIsNotAHeader_()
    : header()
    , a(0)  {
    }
  WithMemberNamedHeaderThatIsNotAHeader_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , a(0)  {
  (void)_alloc;
    }



   typedef  ::test_roscpp::CustomHeader_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator> const> ConstPtr;

}; // struct WithMemberNamedHeaderThatIsNotAHeader_

typedef ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<std::allocator<void> > WithMemberNamedHeaderThatIsNotAHeader;

typedef boost::shared_ptr< ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader > WithMemberNamedHeaderThatIsNotAHeaderPtr;
typedef boost::shared_ptr< ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader const> WithMemberNamedHeaderThatIsNotAHeaderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator1> & lhs, const ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator1> & lhs, const ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_roscpp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59a71bc6c7b0e5643fa9d213cdf4c63c";
  }

  static const char* value(const ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59a71bc6c7b0e564ULL;
  static const uint64_t static_value2 = 0x3fa9d213cdf4c63cULL;
};

template<class ContainerAllocator>
struct DataType< ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_roscpp/WithMemberNamedHeaderThatIsNotAHeader";
  }

  static const char* value(const ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "CustomHeader header\n"
"uint32 a\n"
"================================================================================\n"
"MSG: test_roscpp/CustomHeader\n"
"uint32 a\n"
;
  }

  static const char* value(const ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WithMemberNamedHeaderThatIsNotAHeader_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_roscpp::WithMemberNamedHeaderThatIsNotAHeader_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::test_roscpp::CustomHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "a: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_ROSCPP_MESSAGE_WITHMEMBERNAMEDHEADERTHATISNOTAHEADER_H
