// Generated by gencpp from file test_roscpp/WithTime.msg
// DO NOT EDIT!


#ifndef TEST_ROSCPP_MESSAGE_WITHTIME_H
#define TEST_ROSCPP_MESSAGE_WITHTIME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_roscpp
{
template <class ContainerAllocator>
struct WithTime_
{
  typedef WithTime_<ContainerAllocator> Type;

  WithTime_()
    : my_time()  {
    }
  WithTime_(const ContainerAllocator& _alloc)
    : my_time()  {
  (void)_alloc;
    }



   typedef ros::Time _my_time_type;
  _my_time_type my_time;





  typedef boost::shared_ptr< ::test_roscpp::WithTime_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_roscpp::WithTime_<ContainerAllocator> const> ConstPtr;

}; // struct WithTime_

typedef ::test_roscpp::WithTime_<std::allocator<void> > WithTime;

typedef boost::shared_ptr< ::test_roscpp::WithTime > WithTimePtr;
typedef boost::shared_ptr< ::test_roscpp::WithTime const> WithTimeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_roscpp::WithTime_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_roscpp::WithTime_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_roscpp::WithTime_<ContainerAllocator1> & lhs, const ::test_roscpp::WithTime_<ContainerAllocator2> & rhs)
{
  return lhs.my_time == rhs.my_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_roscpp::WithTime_<ContainerAllocator1> & lhs, const ::test_roscpp::WithTime_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_roscpp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::test_roscpp::WithTime_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_roscpp::WithTime_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_roscpp::WithTime_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_roscpp::WithTime_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_roscpp::WithTime_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_roscpp::WithTime_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_roscpp::WithTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60f189e40cfeaefbc79e6cdbd1605364";
  }

  static const char* value(const ::test_roscpp::WithTime_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60f189e40cfeaefbULL;
  static const uint64_t static_value2 = 0xc79e6cdbd1605364ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_roscpp::WithTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_roscpp/WithTime";
  }

  static const char* value(const ::test_roscpp::WithTime_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_roscpp::WithTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time my_time\n"
;
  }

  static const char* value(const ::test_roscpp::WithTime_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_roscpp::WithTime_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.my_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WithTime_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_roscpp::WithTime_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_roscpp::WithTime_<ContainerAllocator>& v)
  {
    s << indent << "my_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.my_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_ROSCPP_MESSAGE_WITHTIME_H
