// Generated by gencpp from file test_rospy/MultipleAddTwoIntsResponse.msg
// DO NOT EDIT!


#ifndef TEST_ROSPY_MESSAGE_MULTIPLEADDTWOINTSRESPONSE_H
#define TEST_ROSPY_MESSAGE_MULTIPLEADDTWOINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_rospy
{
template <class ContainerAllocator>
struct MultipleAddTwoIntsResponse_
{
  typedef MultipleAddTwoIntsResponse_<ContainerAllocator> Type;

  MultipleAddTwoIntsResponse_()
    : ab(0)
    , cd(0)  {
    }
  MultipleAddTwoIntsResponse_(const ContainerAllocator& _alloc)
    : ab(0)
    , cd(0)  {
  (void)_alloc;
    }



   typedef int32_t _ab_type;
  _ab_type ab;

   typedef int32_t _cd_type;
  _cd_type cd;





  typedef boost::shared_ptr< ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MultipleAddTwoIntsResponse_

typedef ::test_rospy::MultipleAddTwoIntsResponse_<std::allocator<void> > MultipleAddTwoIntsResponse;

typedef boost::shared_ptr< ::test_rospy::MultipleAddTwoIntsResponse > MultipleAddTwoIntsResponsePtr;
typedef boost::shared_ptr< ::test_rospy::MultipleAddTwoIntsResponse const> MultipleAddTwoIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator1> & lhs, const ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ab == rhs.ab &&
    lhs.cd == rhs.cd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator1> & lhs, const ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_rospy

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6fcb876df417a4130d2c7eb2d1b2436";
  }

  static const char* value(const ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6fcb876df417a41ULL;
  static const uint64_t static_value2 = 0x30d2c7eb2d1b2436ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_rospy/MultipleAddTwoIntsResponse";
  }

  static const char* value(const ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 ab\n"
"int32 cd\n"
;
  }

  static const char* value(const ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ab);
      stream.next(m.cd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultipleAddTwoIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_rospy::MultipleAddTwoIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "ab: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ab);
    s << indent << "cd: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_ROSPY_MESSAGE_MULTIPLEADDTWOINTSRESPONSE_H
