// Generated by gencpp from file test_rospy/PythonKeyword.msg
// DO NOT EDIT!


#ifndef TEST_ROSPY_MESSAGE_PYTHONKEYWORD_H
#define TEST_ROSPY_MESSAGE_PYTHONKEYWORD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_rospy
{
template <class ContainerAllocator>
struct PythonKeyword_
{
  typedef PythonKeyword_<ContainerAllocator> Type;

  PythonKeyword_()
    : yield(0)  {
    }
  PythonKeyword_(const ContainerAllocator& _alloc)
    : yield(0)  {
  (void)_alloc;
    }



   typedef int32_t _yield_type;
  _yield_type yield;





  typedef boost::shared_ptr< ::test_rospy::PythonKeyword_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_rospy::PythonKeyword_<ContainerAllocator> const> ConstPtr;

}; // struct PythonKeyword_

typedef ::test_rospy::PythonKeyword_<std::allocator<void> > PythonKeyword;

typedef boost::shared_ptr< ::test_rospy::PythonKeyword > PythonKeywordPtr;
typedef boost::shared_ptr< ::test_rospy::PythonKeyword const> PythonKeywordConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_rospy::PythonKeyword_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_rospy::PythonKeyword_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_rospy::PythonKeyword_<ContainerAllocator1> & lhs, const ::test_rospy::PythonKeyword_<ContainerAllocator2> & rhs)
{
  return lhs.yield == rhs.yield;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_rospy::PythonKeyword_<ContainerAllocator1> & lhs, const ::test_rospy::PythonKeyword_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_rospy

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::test_rospy::PythonKeyword_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_rospy::PythonKeyword_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_rospy::PythonKeyword_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_rospy::PythonKeyword_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_rospy::PythonKeyword_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_rospy::PythonKeyword_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_rospy::PythonKeyword_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1330d6bbfad8e75334346fec949d5133";
  }

  static const char* value(const ::test_rospy::PythonKeyword_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1330d6bbfad8e753ULL;
  static const uint64_t static_value2 = 0x34346fec949d5133ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_rospy::PythonKeyword_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_rospy/PythonKeyword";
  }

  static const char* value(const ::test_rospy::PythonKeyword_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_rospy::PythonKeyword_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 yield\n"
;
  }

  static const char* value(const ::test_rospy::PythonKeyword_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_rospy::PythonKeyword_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.yield);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PythonKeyword_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_rospy::PythonKeyword_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_rospy::PythonKeyword_<ContainerAllocator>& v)
  {
    s << indent << "yield: ";
    Printer<int32_t>::stream(s, indent + "  ", v.yield);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_ROSPY_MESSAGE_PYTHONKEYWORD_H
