// Generated by gencpp from file droidspeak/DroidEmotionResponse.msg
// DO NOT EDIT!


#ifndef DROIDSPEAK_MESSAGE_DROIDEMOTIONRESPONSE_H
#define DROIDSPEAK_MESSAGE_DROIDEMOTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace droidspeak
{
template <class ContainerAllocator>
struct DroidEmotionResponse_
{
  typedef DroidEmotionResponse_<ContainerAllocator> Type;

  DroidEmotionResponse_()
    {
    }
  DroidEmotionResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::droidspeak::DroidEmotionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::droidspeak::DroidEmotionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DroidEmotionResponse_

typedef ::droidspeak::DroidEmotionResponse_<std::allocator<void> > DroidEmotionResponse;

typedef boost::shared_ptr< ::droidspeak::DroidEmotionResponse > DroidEmotionResponsePtr;
typedef boost::shared_ptr< ::droidspeak::DroidEmotionResponse const> DroidEmotionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::droidspeak::DroidEmotionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::droidspeak::DroidEmotionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace droidspeak

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::droidspeak::DroidEmotionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::droidspeak::DroidEmotionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droidspeak::DroidEmotionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droidspeak::DroidEmotionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droidspeak::DroidEmotionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droidspeak::DroidEmotionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::droidspeak::DroidEmotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::droidspeak::DroidEmotionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::droidspeak::DroidEmotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "droidspeak/DroidEmotionResponse";
  }

  static const char* value(const ::droidspeak::DroidEmotionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::droidspeak::DroidEmotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::droidspeak::DroidEmotionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::droidspeak::DroidEmotionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DroidEmotionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::droidspeak::DroidEmotionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::droidspeak::DroidEmotionResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // DROIDSPEAK_MESSAGE_DROIDEMOTIONRESPONSE_H
