// Generated by gencpp from file droidspeak/DroidEmotion.msg
// DO NOT EDIT!


#ifndef DROIDSPEAK_MESSAGE_DROIDEMOTION_H
#define DROIDSPEAK_MESSAGE_DROIDEMOTION_H

#include <ros/service_traits.h>


#include <droidspeak/DroidEmotionRequest.h>
#include <droidspeak/DroidEmotionResponse.h>


namespace droidspeak
{

struct DroidEmotion
{

typedef DroidEmotionRequest Request;
typedef DroidEmotionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DroidEmotion
} // namespace droidspeak


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::droidspeak::DroidEmotion > {
  static const char* value()
  {
    return "3121217addb14943825726ec606b461f";
  }

  static const char* value(const ::droidspeak::DroidEmotion&) { return value(); }
};

template<>
struct DataType< ::droidspeak::DroidEmotion > {
  static const char* value()
  {
    return "droidspeak/DroidEmotion";
  }

  static const char* value(const ::droidspeak::DroidEmotion&) { return value(); }
};


// service_traits::MD5Sum< ::droidspeak::DroidEmotionRequest> should match
// service_traits::MD5Sum< ::droidspeak::DroidEmotion >
template<>
struct MD5Sum< ::droidspeak::DroidEmotionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::droidspeak::DroidEmotion >::value();
  }
  static const char* value(const ::droidspeak::DroidEmotionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::droidspeak::DroidEmotionRequest> should match
// service_traits::DataType< ::droidspeak::DroidEmotion >
template<>
struct DataType< ::droidspeak::DroidEmotionRequest>
{
  static const char* value()
  {
    return DataType< ::droidspeak::DroidEmotion >::value();
  }
  static const char* value(const ::droidspeak::DroidEmotionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::droidspeak::DroidEmotionResponse> should match
// service_traits::MD5Sum< ::droidspeak::DroidEmotion >
template<>
struct MD5Sum< ::droidspeak::DroidEmotionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::droidspeak::DroidEmotion >::value();
  }
  static const char* value(const ::droidspeak::DroidEmotionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::droidspeak::DroidEmotionResponse> should match
// service_traits::DataType< ::droidspeak::DroidEmotion >
template<>
struct DataType< ::droidspeak::DroidEmotionResponse>
{
  static const char* value()
  {
    return DataType< ::droidspeak::DroidEmotion >::value();
  }
  static const char* value(const ::droidspeak::DroidEmotionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DROIDSPEAK_MESSAGE_DROIDEMOTION_H
